C===================================================================
C         This file contains the declarations of functions
C         It is needed to include this file if you use one of these
C         functions. ( to kill warnings "Undeclared Variable"
C         Rusakov A. S.
C==================================================================
      REAL     WAVER, FAVER, TAVER, TRMS, FAVR
      EXTERNAL WAVER, FAVER, TAVER, TRMS, FAVR
      
      REAL     RINTEGR, RINT, AAAVEH
      EXTERNAL RINTEGR, RINT, AAAVEH

      

